version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: toniku/kittygram_backend
    env_file: .env.example
    volumes:
      - static:/backend_static
  frontend:
    image: toniku/kittygram_frontend
    env_file: .env.example
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: toniku/kittygram_gateway
    env_file: .env.example
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles